on:
  workflow_dispatch:
  pull_request:
  pull_request_target:
  push:
    branches: [main]

jobs:
  flake-checker:
    name: "Flake Checker"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
  build:
    name: "Build"
    runs-on: ubuntu-22.04
    needs: [ flake-checker ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: nix build
        run: nix build
  # fmt:
  #   name: "Format"
  #   runs-on: ubuntu-22.04
  #   needs: [ flake-checker ]
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Nix
  #       uses: DeterminateSystems/nix-installer-action@v4
  #     - id: fmt 
  #       run: |
  #         git config user.name '9glenda'
  #         git config user.email 'plan9git@proton.me'
  #         nix fmt
  #         git add -A
  #         git commit -m "fmt" || echo "Nothing to Format"
  #         git push

  flake-check:
    name: "Check"
    runs-on: ubuntu-22.04
    needs: [ flake-checker ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: nix flake check
        run: nix flake check


